### ISSUE TITLE
download.sh

### ISSUE THREAD

**Issue by Decoe** [ArthurSonzogni/ANTLR-cmake-starter#1]
Hi,
thank you for your example. I noticed, that the source zip uri changed, so the download.sh script needs to be adapted (incl. version upgrade) to: 

cd "$(dirname "$0")"
top=$(pwd)

mkdir -p cpp_runtime

## Download ANTLR and the CPP runtime
curl http://www.antlr.org/download/antlr-4.8-complete.jar -o antlr.jar
curl **https://codeload.github.com/antlr/antlr4/zip/4.8** -o cpp_runtime/archive.zip

## Unzip cpp runtime
cd cpp_runtime
unzip archive.zip

**Comment by ArthurSonzogni** [comment]
Thanks! I will update the code soon.
